### ISSUE TITLE
[bug] Worker issue when minified with webpack

### ISSUE THREAD

**Issue by kybarg** [juanelas/bigint-crypto-utils#9]
```log
TypeError [ERR_WORKER_UNSUPPORTED_EXTENSION]: The worker script extension must be \".js\" or \".mjs\". Received \".cjs\"
    at new Worker (internal/worker.js:107:15)
    at \\node_modules\\bigint-crypto-utils\\dist\\cjs\\index.node.cjs:605:35
    at new Promise (<anonymous>)
    at Object.prime (\\node_modules\\bigint-crypto-utils\\dist\\cjs\\index.node.cjs:572:12)
    at SSP.initEncryption (\\node_modules\\encrypted-smiley-secure-protocol\\src\\index.js:91:25)
    at \\dist\\server.js
```

**Comment by juanelas** [comment]
Are you using node 10 when minifying? In that case .cjs is not supported for workers. I wasn't aware of that fact since v10 is no longer supported, and thus I wasn't testing it. In any case, I have generated a .js file that can be used with v10 (just update to v3.0.16) although you need to manually require it.
```javascript
const bigintCryptoUtils = require('bigint-crypto-utils/dist/cjs/index.node')
```
Sorry for the incoveniences and let me know if your issue has been solved.

**Comment by juanelas** [comment]
I assume the issue has been solved.

**Comment by kybarg** [comment]
@juanelas dont think so, we moved to another solution
